stages:
  train_risk:
    cmd: python -m src.training_pipeline --model risk
    deps:
    - outputs/model_table.csv
    - src
    outs:
    - models/risk_model_complete_pipeline.joblib
  train_claim:
    cmd: python -m src.training_pipeline --model claim
    deps:
    - outputs/model_table.csv
    - src
    outs:
    - models/claim_model_complete_pipeline.joblib
